### ISSUE TITLE
독서실/도서관/카페 공부 데이트

### ISSUE THREAD

**Issue by 20chan** [phillyai/bucket-list#31]
같이 공부하자 와 공부 좋아

**Comment by 20chan** [comment]
![20181224_171559](https://user-images.githubusercontent.com/16171816/50422044-3557d080-0889-11e9-9204-6e7463229a00.jpg)

공부하다 갑자기 이 이슈가 떠올라서 저 페이지가 모니터에 떠있지만 원래는 cirno.Numerics 코딩하고 있었다. 암튼 공부 열심히 했음. 3시간정도 했음. 정말ㄹ로

**Comment by curaai** [comment]
<흑역사>
